# Generated by Django 4.2.7 on 2023-12-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('circuito', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('aereo', models.CharField(max_length=50)),
                ('traslados', models.CharField(max_length=50)),
                ('comidas', models.CharField(max_length=50)),
            ],
        ),
    ]
